input_type = ""
raw_test = ""
raw_corr_type = ""
raw_mr_outcomevar = ""
raw_indttest_groupvar = ""
raw_pairttest_inputVars_list = ""

summ_corr_varOne = ""
summ_corr_varTwo = ""
summ_corr_coeff = ""
summ_indttest_var = ""
summ_indttest_meanOne = ""
summ_indttest_sdOne = ""
summ_indttest_nOne = ""
summ_indttest_meanTwo = ""
summ_indttest_sdTwo = ""
summ_indttest_nTwo = ""
summ_indttest_equal_var = ""

spss_test = ""
spss_indttest_nOne = ""
spss_indttest_nTwo = ""
spss_indttest_groupOneLabel = ""
spss_indttest_groupTwoLabel = ""
spss_pairttest_nOne = ""
spss_pairttest_nTwo = ""

effect_size_choice = ""
correction_type = ""

raw_ttest_output_descriptives = ""
non_numeric_input_raise_errors = ""
output_pvalues_type = ""

input_filename = ""
input_fileext = ""
alpha_threshold = ""
output_dir = ""