# This is a basic workflow to help you get started with Actions

name: Windows-Dist

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: windows-latest
    defaults:
      run:
        working-directory: ./Source Code

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    # Set up python env
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    # Install dependencies
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pyinstaller
        
    # Run tests
    - name: Run tests
      run: |
        python tests__main.py
        
    # Build executable distribution
    - name: PyInstaller
      run: |
        pyinstaller mufosGenericSpec.spec

    # Upload distribution as an artifact
    - name: Upload dist as an artifact
      uses: actions/upload-artifact@v2
      with:
          name: dist-windows
          path: dist/mufos